update ExperimentDesign-definition.yml
ElucidataInc/TranscriptomeInsight pull request #1
Opened 2024-04-26 11:07 UTC by ishitasati11

2024-04-26 11:17 UTC, KrutikaGaonkar approved these changes

2024-04-26 11:21 UTC, pverma12394 commented on DataModel/ExperimentDesign/ExperimentDesign-definition.yml
> +    cellLine:
@ishitasati11 Let's also add a field called `pattern` with each attribute where certain rules can be applied for better validation. For instance all cell line IDs must start with `CVCL` so it is assigned a regex pattern.

2024-04-26 11:22 UTC, pverma12394 commented on DataModel/ExperimentDesign/ExperimentDesign-definition.yml
>        type: string
@ishitasati11 This should be an integer right?

2024-04-26 11:24 UTC, pverma12394 commented on DataModel/ExperimentDesign/ExperimentDesign-definition.yml
>      totalNumberSamples:
@ishitasati11 Can we add a limit for numerical attributes, as in, 
`lower limit` and `upper limit`. It would be nice to have it!

2024-04-26 11:25 UTC, pverma12394 requested changes
Please review the comments.

2024-04-29 12:20 UTC, pverma12394 commented on DataModel/ExperimentDesign/ExperimentDesign-definition.yml
>        type: string
@ishitasati11 `type: integer`

2024-04-30 09:32 UTC, pverma12394 approved these changes

2024-04-30 09:32 UTC, merged